adflash: add clean support

diff --git a/_archidroid/auto/system/bin/adflash b/_archidroid/auto/system/bin/adflash
--- a/_archidroid/auto/system/bin/adflash
+++ b/_archidroid/auto/system/bin/adflash
@@ -49,6 +49,7 @@ if [ $# -eq 0 ]; then
 	echo "Currently using mode: $MODE. If you're satisfied with this mode you can just skip this question"
 	echo "git			Sets up local git repository, which gives you delta upgrades and bandwidth saving"
 	echo "direct		Downloads targeted branch as .zip file directly from github"
+	echo "clean			Cleans everything up, including local repo and tmp folder from ArchiDroid directory specified below"
 	echo ""
 	echo "ArchiDroid will prioritize extsd if it contains ArchiDroid folder and eventually fall back to intsd, you can override this here"
 	echo "Currently using ArchiDroid in: $AD. If you're satisfied with this path you can just skip this question"
@@ -64,28 +65,8 @@ if [ $# -eq 0 ]; then
 	read EXTRA
 else
 	VERSION="$1"
-	shift 1
 	EXTRA="$@"
 fi
-
-case "$VERSION" in
-	"2e")
-		VERSION="2.X-EXPERIMENTAL"
-		;;
-	"2s")
-		VERSION="2.X-STABLE"
-		;;
-	"1e")
-		VERSION="1.X-EXPERIMENTAL"
-		;;
-	"1s")
-		VERSION="1.X-STABLE"
-		;;
-	*)
-		echo "Sorry, could not detect any valid version, exiting"
-		exit 1
-esac
-echo "Ok, detected $VERSION"
 
 # Parse extra args
 for arg in $EXTRA; do
@@ -95,6 +76,13 @@ for arg in $EXTRA; do
 			;;
 		"direct")
 			MODE="direct"
+			;;
+		"clean")
+			echo "Cleaning..."
+			rm -rf $AD/tmp
+			rm -rf $AD/GitHub
+			echo "Done, Removed $AD/tmp and $AD/GitHub folders"
+			exit 0
 			;;
 		"nozip")
 			NOZIP=1
@@ -144,6 +132,24 @@ for arg in $EXTRA; do
 			continue
 	esac
 done
+
+case "$VERSION" in
+	"2e")
+		VERSION="2.X-EXPERIMENTAL"
+		;;
+	"2s")
+		VERSION="2.X-STABLE"
+		;;
+	"1e")
+		VERSION="1.X-EXPERIMENTAL"
+		;;
+	"1s")
+		VERSION="1.X-STABLE"
+		;;
+	*)
+		echo "Sorry, could not detect any valid version, exiting"
+		exit 1
+esac
 
 echo ""
 echo "Testing your internet connection..."
@@ -207,6 +213,7 @@ if [ "$MODE" == "direct" ]; then
 		exit 1
 	fi
 
+	rm -f archidroid_github.zip
 	cd _adflash/ArchiDroid-$VERSION
 	if [ $? -ne 0 ]; then
 		echo "Something went wrong, aborting"
