Add local option to adflasher

diff --git a/_archidroid/auto/system/bin/adflash b/_archidroid/auto/system/bin/adflash
--- a/_archidroid/auto/system/bin/adflash
+++ b/_archidroid/auto/system/bin/adflash
@@ -3,8 +3,12 @@
 VERSION=""
 TEMP=""
 AD="/data/media/0/ArchiDroid"
+
+echo "Welcome to ArchiDroid Command Line Flasher!"
+echo "Checking access to $AD"
+(mkdir -p $AD/tmp && touch $AD/test && rm -f $AD/test && echo "Test passed, we're ready to go!") || (echo "Sorry, access test failed. It looks like I need root" && exit 1)
+
 if [ $# -eq 0 ]; then
-	echo "Welcome to ArchiDroid Command Line Flasher!"
 	echo "Usage: $0 [VERSION]"
 	echo ""
 	echo "Available versions:"
@@ -12,15 +16,13 @@ if [ $# -eq 0 ]; then
 	echo "2s	2.X-STABLE"
 	echo "1e	1.X-EXPERIMENTAL"
 	echo "1s	1.X-STABLE"
+	echo "local	If you have $AD/tmp/archidroid_github.zip downloaded already"
 	echo ""
 	echo -n "Your choice: "
 	read VERSION
 else
 	VERSION="$1"
 fi
-
-echo "Checking access to $AD"
-(mkdir -p $AD/tmp && touch $AD/test && rm -f $AD/test && echo "Test passed, we're ready to go!") || (echo "Sorry, access test failed. It looks like I need root" && exit 1)
 
 case "$VERSION" in
 	"2e")
@@ -35,6 +37,9 @@ case "$VERSION" in
 	"1s")
 		TEMP="1.X-STABLE"
 		;;
+	"local")
+		TEMP="local"
+		;;
 	*)
 		echo "Sorry, could not detect any valid version, exiting"
 		exit 1
@@ -44,20 +49,27 @@ TEMP=""
 echo "Ok, detected $VERSION"
 
 (cd $AD/tmp && rm -rf _adflash && rm -f $AD/ArchiDroid.zip) || (echo "Unknown error, aborting" && exit 1)
-
-curl -kSs https://raw.github.com/JustArchi/ArchiDroid/$VERSION/META-INF/com/google/android/aroma/_changelog.txt
-echo ""
-echo ""
 cd $AD/tmp
-echo "Ok, starting download from GitHub"
-echo "Warning, it may take long time. Make sure that you have stable Wi-Fi connection"
-TEMP=`curl -kISs https://codeload.github.com/JustArchi/ArchiDroid/zip/$VERSION | grep "Content-Length" | awk '{print $2}'`
-TEMP=`expr $TEMP / 1000000`
-echo "It's about $TEMP Megabytes"
-TEMP=""
-echo "Downloading right now..."
-curl -Sk https://codeload.github.com/JustArchi/ArchiDroid/zip/$VERSION > archidroid_github.zip || (echo "Download failed, aborting" && exit 1)
-echo "Download completed, it took some time..."
+
+if [ "$VERSION" != "local" ]; then
+	curl -kSs https://raw.github.com/JustArchi/ArchiDroid/$VERSION/META-INF/com/google/android/aroma/_changelog.txt
+	echo ""
+	echo ""
+	echo "Ok, starting download from GitHub"
+	echo "Warning, it may take long time. Make sure that you have stable Wi-Fi connection"
+	TEMP=`curl -kISs https://codeload.github.com/JustArchi/ArchiDroid/zip/$VERSION | grep "Content-Length" | awk '{print $2}'`
+	TEMP=`expr $TEMP / 1000000`
+	echo "It's about $TEMP Megabytes"
+	TEMP=""
+	echo "Downloading right now..."
+	curl -Sk https://codeload.github.com/JustArchi/ArchiDroid/zip/$VERSION > archidroid_github.zip || (echo "Download failed, aborting" && exit 1)
+	echo "Download completed, it took some time..."
+fi
+
+if [ ! -e archidroid_github.zip ]; then
+	echo "Couldn't find $AD/tmp/archidroid_github.zip, aborting" && exit 1
+fi
+
 echo "Repacking downloaded ArchiDroid"
 echo "Unzipping ArchiDroid in GitHub version"
 mkdir _adflash
