Updated pocket debian, Adlinux code review

diff --git a/_archidroid/auto/system/bin/adlinux b/_archidroid/auto/system/bin/adlinux
--- a/_archidroid/auto/system/bin/adlinux
+++ b/_archidroid/auto/system/bin/adlinux
@@ -1,271 +1,259 @@
 #!/system/bin/sh
 
-# ArchiDroid Debian/Linux Booter
+#     _             _     _ ____            _     _
+#    / \   _ __ ___| |__ (_)  _ \ _ __ ___ (_) __| |
+#   / _ \ | '__/ __| '_ \| | | | | '__/ _ \| |/ _` |
+#  / ___ \| | | (__| | | | | |_| | | | (_) | | (_| |
+# /_/   \_\_|  \___|_| |_|_|____/|_|  \___/|_|\__,_|
+#
+# Copyright 2014 Łukasz "JustArchi" Domeradzki
+# Contact: JustArchi@JustArchi.net
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 
-SSHD=false
-VNCD=false
+AD="/data/media/0/ArchiDroid"
+SSHD=0
+VNCD=0
+EXTSD=0
+EXTSDSUPPORTED=0
+MOUNTCORE=0
+MOUNTSTORAGE=0
 
-if [ `whoami 2>&1 | grep -i "root" | wc -l` -eq 0 ] && [ `whoami 2>&1 | grep -i "uid 0" | wc -l` -eq 0 ]; then
-	echo "Sorry, but I require root access, please execute me as root"
+if [[ "$(whoami 2>&1 | grep -c "root")" -eq 0 && "$(whoami 2>&1 | grep -c "uid 0")" -eq 0 ]]; then
+	echo "Sorry, but this utility requires root access"
+	echo "Executed as: $(whoami)"
 	exit 1
 fi
 
-if [ -d /storage/sdcard1/ArchiDroid ]; then
-	NOEXTSD=false
-	AD="/storage/sdcard1/ArchiDroid"
-	ln -s $AD /storage/sdcard1/adtest >/dev/null 2>&1
-	if [ $? -ne 0 ]; then
-		AD="/data/media/0/ArchiDroid"
-		EXTSDSUPPORTED=false
-	else
-		rm -f /storage/sdcard1/adtest
-		EXTSDSUPPORTED=true
+for ADPATH in "/storage/sdcard1 /storage/extSdCard"; do
+	if [[ -d "$ADPATH" ]]; then
+		EXTSD=1
+		EXTSDPATH="$ADPATH"
+		ln -s "$AD" "$EXTSDPATH/adtest" >/dev/null 2>&1
+		if [[ $? -eq 0 ]]; then
+			rm -f "$EXTSDPATH/adtest"
+			EXTSDSUPPORTED=1
+		else
+			EXTSDSUPPORTED=0
+		fi
+		if [[ "$EXTSDSUPPORTED" -eq 1 && -d "$EXTSDPATH/ArchiDroid" ]]; then
+			AD="$EXTSDPATH/ArchiDroid"
+		fi
+		break
 	fi
-elif [ -d /storage/extSdCard/ArchiDroid ]; then
-	NOEXTSD=false
-	AD="/storage/extSdCard/ArchiDroid"
-	ln -s $AD /storage/extSdCard/adtest >/dev/null 2>&1
-	if [ $? -ne 0 ]; then
-		AD="/data/media/0/ArchiDroid"
-		EXTSDSUPPORTED=false
-	else
-		rm -f /storage/extSdCard/adtest
-		EXTSDSUPPORTED=true
-	fi
-else
-	NOEXTSD=true
-	AD="/data/media/0/ArchiDroid"
-fi
+done
 
-mnt=$AD/debian
+ADMNT="$AD/debian"
 
 echo "Welcome to ArchiDroid Debian/Linux Booter!"
-echo "Checking access to $AD"
-mkdir -p $AD/tmp
-cd $AD/tmp && rm -f test && touch test && rm -f test
-CHECK1=$?
-if [ $CHECK1 -ne 0 ]; then
-	echo "Sorry, access test failed. Make sure that $AD/tmp is not being owned by root or give me root access"
-	exit 1
-else
-	echo "Access test passed, we're ready to go!"
-fi
 
 if [ $# -eq 0 ]; then
-	echo "Usage: $(basename $0) <MODE> [EXTRA]"
+	echo "Usage: $(basename "$0") [MODE] [EXTRA FLAGS]"
 	echo
 	echo "Available modes:"
 	echo
-	echo "default		Will mount /data /system /storage/sdcard0 /storage/sdcard1 and core filesystems in chroot. Default suggested mode"
+	echo "default    Mounts /data /system /storage/sdcard0 /storage/sdcard1 and core filesystems in chroot. Default suggested mode"
 	echo
-	echo "safe			Will mount only core filesystems in chroot. Useful if you don't want to share your storage in chroot"
+	echo "safe       Mounts only core filesystems in chroot. Useful if you don't want to share your storage in chroot"
 	echo
-	echo "bare			Won't mount even core filesystems such as /proc /dev or /sys. Requires \"debian force\" to enter chroot. This is the \"real\" safe mode. You won't be able to interact with an android in any way, while debian itself will work in very limited environment, making core functions unavailable. Suggested only for testing purposes"
+	echo "bare       Doesn't mount even core filesystems such as /proc /dev or /sys. Requires \"debian force\" to enter chroot. This is the \"real\" safe mode. You won't be able to interact with an android in any way, while debian itself will work in very limited environment, making core functions unavailable. Not suggested"
 	echo
-	echo "rebuild		Will automatically reboot your device and remove debian folder in the safe way. WILL CAUSE ALL DEBIAN DATA TO BE LOST!"
+	echo "rebuild    Reboots your device and removes debian folder in the safe way. All debian's data (in $ADMNT) will be lost!"
 	echo
-	echo "unmount		Will automatically reboot your device to safely unmount debian environment"
+	echo "unmount    Unmounts your pocket debian. As for now unmounting requires reboot, so this works the same as rebooting your device"
 	echo
-	echo -n "Your choice: "
+	printf "Choice: "
 	read CHOICE
 	echo
 	echo
-	echo "You may specify any extra options here separated by a whitespace. Eventually you can just skip this question and apply defaults"
+	echo "You may specify extra options here separated by a whitespace. You can also just skip this question and apply default settings"
 	echo
-	if (! $NOEXTSD); then
-		echo "ArchiDroid will prioritize extsd if it contains ArchiDroid/debian folder and eventually fall back to intsd, you can override this here"
-		echo "Currently using ArchiDroid in: $AD. If you're satisfied with this path you can just skip this question"
-		echo "WARNING! Debian requires symlink functionality, typically native windows filesystems DON'T support symlinks, therefore you need to have your external sd card formatted in one of the native linux filesystems, f.e. ext4"
-		if ($EXTSDSUPPORTED); then
-			echo "ArchiDroid Detect: Your external sd card IS supported"
-		else
-			echo "ArchiDroid Detect: Your external sd card IS NOT supported"
-		fi
-		echo
-		echo "extsd			Use external sd card (/storage/sdcard1 /storage/extSdCard), if possible"
-		echo
-		echo "intsd			Use internal sd card (/data/media/0)"
-		echo
-		echo
+	echo "ArchiDroid will prioritize external sd card if it contains ArchiDroid/debian folder already and fall back to intsd otherwise, you can override this here"
+	echo "Currently using ArchiDroid in: $AD. If you're satisfied with this path you can just skip this question"
+	echo "WARNING! Debian requires symlink functionality, typically native windows filesystems DON'T support symbolic links, therefore you need to have your external sd card formatted in one of the native linux filesystems, e.g. ext4"
+	if [[ "$EXTSDSUPPORTED" -eq 1 ]]; then
+		echo "ArchiDroid Detect: Your external sd card IS supported"
+	else
+		echo "ArchiDroid Detect: Your external sd card IS NOT supported"
 	fi
-	echo "ArchiDroid is able to start a number of services after debian boot up, this can save your time doing so manually"
 	echo
-	echo "ssh		Will start Secure Shell Daemon after debian boot"
+	echo "extsd    Use external sd card (/storage/sdcard1 /storage/extSdCard), if possible"
 	echo
-	echo "vnc		Will start VNC Daemon after debian boot"
+	echo "intsd    Use internal sd card (/data/media/0)"
 	echo
 	echo
-	echo "Example: vnc ssh"
-	echo -n "Your extra options: "
+	echo "ArchiDroid is able to start a number of services after debian boots up, this can save your time doing so manually"
+	echo
+	echo "ssh    Will start Secure Shell Daemon after debian boot"
+	echo
+	echo "vnc    Will start VNC Daemon after debian boot"
+	echo
+	echo
+	echo "Example: intsd ssh"
+	echo -n "Extra options: "
 	read EXTRA
 else
 	CHOICE="$1"
-	shift 1
-	EXTRA="$@"
+	shift
+	EXTRA="$*"
 fi
 
 # Parse extra args
-for arg in $EXTRA; do
-	case "$arg" in
-		"intsd")
+for ARG in $EXTRA; do
+	case "$ARG" in
+		--intsd|intsd)
 			if [ "$AD" != "/data/media/0/ArchiDroid" ]; then
-				echo "Changing path to internal sd!"
+				echo "Overriding ArchiDroid path to internal sd card!"
 				AD="/data/media/0/ArchiDroid"
-				mkdir -p $AD/tmp
-				cd $AD/tmp && rm -f test && touch test && rm -f test
-				CHECK1=$?
-				if [ $CHECK1 -ne 0 ]; then
-					echo "Sorry, access test failed. Make sure that $AD/tmp is not being owned by root or give me root access"
-					exit 1
-				else
-					echo "Access test passed, we're ready to go!"
-					mnt=$AD/debian
-				fi
+				ADMNT="$AD/debian"
 			fi
 			;;
-		"extsd")
-			if [ "$AD" == "/data/media/0/ArchiDroid" ] && ($EXTSDSUPPORTED); then
-				echo "Changing path to external sd!"
-				if [ -e /storage/sdcard1 ]; then
-					AD="/storage/sdcard1/ArchiDroid"
-				elif [ -e /storage/extSdCard ]; then
-					AD="/storage/extSdCard/ArchiDroid"
-				fi
-
-				if [ "$AD" != "/data/media/0/ArchiDroid" ]; then
-					mkdir -p $AD/tmp
-					cd $AD/tmp && rm -f test && touch test && rm -f test
-					CHECK1=$?
-					if [ $CHECK1 -ne 0 ]; then
-						echo "Sorry, access test failed. Make sure that $AD/tmp is not being owned by root or give me root access"
-						exit 1
-					else
-						echo "Access test passed, we're ready to go!"
-						mnt=$AD/debian
-					fi
-				else
-					echo "Sorry, could not detect any valid path to use"
-					echo "You selected extsd and I failed to use it so I'm aborting here"
-					exit 1
-				fi
-			elif [ "$AD" == "/data/media/0/ArchiDroid" ] && (! $EXTSDSUPPORTED); then
-				echo "You selected extsd, but I failed to use it so I'm aborting here"
-				echo "It lacks symlink functionality, you need to reformat your external sd card to native linux filesystem (f.e. ext4) if you want to use debian on your extsd"
+		--extsd|extsd)
+			if [[ "$EXTSDSUPPORTED" -eq 1 ]]; then
+				echo "Overriding ArchiDroid path to external sd card!"
+				AD="$EXTSDPATH"
+				ADMNT="$AD/debian"
+			else
+				echo "You selected external sd card, but it's not available because of broken Linux symbolic links functionality"
+				echo "You need to reformat your external sd card to native linux filesystem (e.g. ext4) if you want to use debian on your external sd card"
 				exit 1
 			fi
 			;;
-		"ssh")
-			SSHD=true
+		--ssh|ssh)
+			SSHD=1
 			;;
-		"vnc")
-			VNCD=true
+		--vnc|vnc)
+			VNCD=1
 			;;
 		*)
 	esac
 done
 
 case "$CHOICE" in
-	"unmount")
+	--unmount|unmount)
+		sync
 		reboot
 		exit 0
 		;;
-	"rebuild")
+	--rebuild|rebuild)
 		sysrw
-
-echo "#!/system/bin/sh
-rm -rf $mnt
-sysrw
-rm -f \$0
-sysro
-exit 0" > /system/etc/init.d/91ArchiDroid_RebuildDebian
-
+		{
+			echo "#!/system/bin/sh"
+			echo "rm -rf $ADMNT"
+			echo "sysrw"
+			echo "rm -f \$0"
+			echo "sysro"
+			echo "exit 0"
+		} > /system/etc/init.d/91ArchiDroid_RebuildDebian
 		chmod 755 /system/etc/init.d/91ArchiDroid_RebuildDebian
-		busybox sync
+		sync
 		reboot
 		exit 0
 		;;
-	"default")
-		echo "Ok, detected $CHOICE"
-		;;
-	"safe")
-		echo "Ok, detected $CHOICE"
-		;;
-	"bare")
-		echo "Ok, detected $CHOICE"
-		;;
+	--default|default) MOUNTCORE=1; MOUNTSTORAGE=1 ;;
+	--safe|safe) MOUNTCORE=1 ;;
+	--bare) ;;
 	*)
-		echo "Sorry, could not detect any valid choice, exiting"
+		echo "Sorry, $CHOICE is not a valid choice, exiting"
 		exit 1
 esac
 
-if [ -e $mnt/proc/uptime ] && [ -e $mnt/dev/urandom ] && [ -e $mnt/sys/kernel ]; then
-	echo "It looks like your debian is already booted, skipping booting and mode selection..."
+if [[ -e "$ADMNT/proc/uptime" && -e "$ADMNT/dev/urandom" && -e "$ADMNT/sys/kernel" ]]; then
+	echo "ArchiDroid's Pocket Debian is already booted!"
 else
-	echo "It looks like your debian isn't booted yet, booting..."
+	if [ ! -e "$ADMNT/bin/bash" ]; then
+		echo "This is your first installation!"
+		echo
+		echo "User: root"
+		echo "Password: archidroid$"
+		echo "You can change default password via \"passwd\" command after you login"
+		echo
+		echo "Please note that using \"adlinux\" or \"debian\" commands doesn't require a password"
+		echo "However, password is required e.g. for accessing OpenSSH server"
+		echo
+		echo "Installing ArchiDroid's Pocket Debian in $ADMNT..."
+		mkdir -p "$ADMNT"
+		busybox tar -zxf /system/archidroid/system/debian.tar.gz -C "$ADMNT"
 
-	if [ ! -e $mnt/bin/bash ]; then
-		mkdir -p $mnt
-		echo "It looks like it's your first installation. Unpacking your debian..."
-		busybox tar -zxf /system/archidroid/system/debian.tar.gz -C $mnt
-		cp /file_contexts $mnt
-		debian "force" "cmd" "ln -s /proc/mounts /etc/mtab"
+		echo "Cleanup..."
+		cp /file_contexts "$ADMNT" # We need SELinux context or various apps will go crazy
+		debian "force" "cmd" "ln -s /proc/mounts /etc/mtab" # This is done automatically on most distros on first boot, but we don't have Debian's /init
+		debian "force" "cmd" "sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/g' /etc/ssh/sshd_config" # Newer versions of SSH deny root access by default now, and since we don't have any other user, we need it
+		debian "force" "cmd" "echo -e 'archidroid$\narchidroid$' | passwd >/null.txt 2>&1" # By default there's no password for root required by SSH, this fixes it
+		debian "force" "cmd" "rm -f /null.txt" # We don't have /dev/null mounted at this stage
 		echo "Done!"
 	fi
 
-	echo "Booting debian..."
+	echo "Booting ArchiDroid's Pocket Debian..."
 
-	case "$CHOICE" in
-	"default")
-		echo "Mounting /dev /dev/pts /dev/shm /proc /sys /tmp /system /data /storage/sdcard0 /storage/sdcard1"
-		mkdir -p $mnt/dev && busybox mount --bind /dev $mnt/dev
-		mkdir -p $mnt/dev/pts && busybox mount --bind /dev/pts $mnt/dev/pts
-		mkdir -p $mnt/dev/shm && busybox mount --bind /dev/shm $mnt/dev/shm
-		mkdir -p $mnt/proc && busybox mount -t proc proc $mnt/proc
-		mkdir -p $mnt/sys && busybox mount -t sysfs sysfs $mnt/sys
-		mkdir -p $mnt/tmp && busybox mount -t tmpfs tmpfs $mnt/tmp
-		mkdir -p $mnt/system && busybox mount --bind /system $mnt/system
-		mkdir -p $mnt/data && busybox mount --bind /data $mnt/data
-		mkdir -p $mnt/storage/sdcard0 && busybox mount --bind /storage/sdcard0 $mnt/storage/sdcard0
-		
-		if [ -e /storage/sdcard1 ]; then
-			mkdir -p $mnt/storage/sdcard1 && busybox mount --bind /storage/sdcard1 $mnt/storage/sdcard1
-			busybox umount -f $mnt/storage/extSdCard >/dev/null 2>&1 && rmdir $mnt/storage/extSdCard
-		elif [ -e /storage/extSdCard ]; then
-			mkdir -p $mnt/storage/extSdCard && busybox mount --bind /storage/extSdCard $mnt/storage/extSdCard
-			busybox umount -f $mnt/storage/sdcard1 >/dev/null 2>&1 && rmdir $mnt/storage/sdcard1
+	if [[ "$MOUNTCORE" -eq 1 ]]; then
+		echo "Mounting core filesystems..."
+		mkdir -p "$ADMNT/dev" && busybox mount --bind /dev "$ADMNT/dev"
+		mkdir -p "$ADMNT/dev/pts" && busybox mount --bind /dev/pts "$ADMNT/dev/pts"
+		mkdir -p "$ADMNT/dev/shm" && busybox mount --bind /dev/shm "$ADMNT/dev/shm"
+		mkdir -p "$ADMNT/proc" && busybox mount -t proc proc "$ADMNT/proc"
+		mkdir -p "$ADMNT/sys" && busybox mount -t sysfs sysfs "$ADMNT/sys"
+		mkdir -p "$ADMNT/tmp" && busybox mount -t tmpfs tmpfs "$ADMNT/tmp"
+		if [[ "$MOUNTSTORAGE" -eq 1 ]]; then
+			echo "Mounting storages..."
+			mkdir -p "$ADMNT/system" && busybox mount --bind /system "$ADMNT/system"
+			mkdir -p "$ADMNT/data" && busybox mount --bind /data "$ADMNT/data"
+			mkdir -p "$ADMNT/storage/sdcard0" && busybox mount --bind /storage/sdcard0 "$ADMNT/storage/sdcard0"
+			mkdir -p "$ADMNT/storage/sdcard0" && busybox mount --bind /storage/sdcard0 "$ADMNT/storage/sdcard0"
+			if [[ "$EXTSD" -eq 1 ]]; then
+				mkdir -p "$ADMNT/$EXTSDPATH" && busybox mount --bind "$EXTSDPATH" "$ADMNT/$EXTSDPATH"
+			fi
 		fi
-		;;
-	"safe")
-		echo "Mounting /dev /dev/pts /dev/shm /proc /sys /tmp, SKIPPING /system /data /storage/sdcard0 /storage/sdcard1"
-		mkdir -p $mnt/dev && busybox mount --bind /dev $mnt/dev
-		mkdir -p $mnt/dev/pts && busybox mount --bind /dev/pts $mnt/dev/pts
-		mkdir -p $mnt/dev/shm && busybox mount --bind /dev/shm $mnt/dev/shm
-		mkdir -p $mnt/proc && busybox mount -t proc proc $mnt/proc
-		mkdir -p $mnt/sys && busybox mount -t sysfs sysfs $mnt/sys
-		mkdir -p $mnt/tmp && busybox mount -t tmpfs tmpfs $mnt/tmp
-		;;
-	"bare")
-		echo "Not mounting anything!"
-		;;
-	*)
-		echo "Sorry, could not detect any valid choice, exiting"
-		exit 1
-	esac
+	fi
 fi
 
-echo "ArchiDroid Debian environment ready!"
-echo "Type \"debian\" to enter chroot"
+echo "ArchiDroid's Pocket Debian is ready!"
 echo
 
-if ($SSHD); then
+PRINTIFCONFIG=0
+if [[ "$SSHD" -eq 1 ]]; then
+	PRINTIFCONFIG=1
 	echo "Starting Secure Shell Daemon!"
-	debian "cmd" "service ssh start"
+	debian "force" "cmd" "service ssh start"
+	echo "You can access OpenSSH server via any SSH client such as PuTTY. OpenSSH is listening on default 22 port"
 fi
-if ($VNCD); then
+if [[ "$VNCD" -eq 1 ]]; then
+	PRINTIFCONFIG=1
 	echo "Starting VNC Daemon!"
-	debian "cmd" "rm -f /root/.vnc/*.pid"
-	debian "cmd" "rm -f /root/.vnc/*.log"
-	debian "cmd" "tightvncserver -geometry 1280x720"
+	debian "force" "cmd" "rm -f /root/.vnc/*.pid"
+	debian "force" "cmd" "rm -f /root/.vnc/*.log"
+	debian "force" "cmd" "tightvncserver -geometry 1280x720"
+	echo "You can access VNCD server via any VNC client such as VNC Viewer. VNCD is listening on default 5901 port"
+	echo
+	echo "Please note that ArchiDroid's Pocket Debian does NOT include any graphical user interafce by default (only graphical terminal)"
+	echo "You need to install one if you want to use it"
+	echo "The easiest way to achieve that is typing \"debian\" command, then \"apt-get update && apt-get install GUI\""
+	echo "Where GUI could be one of the following: lxde xfce4 kde-standard kde-full gnome-core gnome"
+	echo "Suggested by ArchiDroid: lxde, xfce4 - both of them are very lightweight, and this is core thing for our little Android devices"
+	echo "Please note that you must restart VNCD after installing GUI of your choice. Rebooting your device and starting adlinux in vnc mode again will do the trick"
+fi
+
+if [[ "$PRINTIFCONFIG" -eq 1 ]]; then
+	echo
+	echo "You can now access your ArchiDroid's Pocket Debian remotely!"
+	echo "Here are currently available local IPs, which may help you:"
+	busybox ifconfig | grep "cast"
+	echo "If you want to check more, \"busybox ifconfig\" may help"
+	echo "Please note that only people in your LAN (e.g. connected to the same Wi-Fi router) can access ArchiDroid's Pocket Debian on this device"
+else
+	echo "You didn't start any service for accessing your ArchiDroid's Pocket Debian remotely"
+	echo "This is OK if you know what you're doing. You can still access your debian with \"debian\" command"
+	echo "If that's not a case, execute adlinux again and don't forget to specify ssh/vnc switch this time!"
 fi
 
 exit 0
