Pocket debian improvements

diff --git a/_archidroid/auto/system/bin/debian b/_archidroid/auto/system/bin/debian
--- a/_archidroid/auto/system/bin/debian
+++ b/_archidroid/auto/system/bin/debian
@@ -3,8 +3,13 @@
 AD="/data/media/0/ArchiDroid"
 mnt=$AD/debian
 
-if [ ! -e $mnt/proc/uptime ]; then
-	adlinux "unsafe"
+if [ "$1" != "force" ]; then
+	if [ ! -e $mnt/proc/uptime ] || [ ! -e $mnt/dev/urandom ] || [ ! -e /sys/kernel ]; then
+		echo "Warning! It looks like you didn't mount required dev, proc and sys filesystems!"
+		echo "Did you forget to call \"adlinux\" command firstly?"
+		echo "If you know what you're doing and you're trying to load bare debian chroot, try \"debian force\" to proceed"
+		exit 1
+	fi
 fi
 
 export TERM=linux
@@ -14,5 +19,6 @@ if [ `echo $PATH | grep "/usr/local/sbin" | wc -l` -eq 0 ]; then
 		export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
 fi
 
+cat $mnt/etc/motd
 chroot $mnt /bin/bash
 exit 0
