Proper fixes

diff --git a/_archidroid/auto/system/etc/init.d/99ArchiDroid_Init b/_archidroid/auto/system/etc/init.d/99ArchiDroid_Init
--- a/_archidroid/auto/system/etc/init.d/99ArchiDroid_Init
+++ b/_archidroid/auto/system/etc/init.d/99ArchiDroid_Init
@@ -10,17 +10,18 @@
 AD="/data/media/0/ArchiDroid"
 LOG="$AD/Init.log" # "/dev/null" is no verbose
 
-# Redirect stderr and stdout to our log, just in case something bad happen
-exec 1>$LOG # Use "exec 1>>$LOG" for append
-exec 2>&1
+# Redirect stderr to our log, just in case something bad happen
+#exec 1>$LOG # Use "exec 1>>$LOG" for append
+echo -n "" > $LOG
+exec 2>>$LOG
 
-echo "`date`"
-echo "`uname -a`"
-echo "INFO: ArchiDroid_Init executed!"
+echo "`date`" >> $LOG
+echo "`uname -a`" >> $LOG
+echo "INFO: ArchiDroid_Init executed!" >> $LOG
 
 if [ -e /system/etc/init.d/98ArchiDroid_RunOnce ]; then
 	# This is our first boot, don't call init yet
-	echo "INFO: This is our first boot, I'll let RunOnce finish his job, exiting...
+	echo "INFO: This is our first boot, I'll let RunOnce finish his job, exiting... >> $LOG
 	exit 2
 fi
 
@@ -39,47 +40,47 @@ fi
 
 # Cool ArchiDroid Banner
 if [ -e /system/bin/boot-dmesg ]; then
-	echo "INFO: boot-dmesg detected, turning on logcat banner"
+	echo "INFO: boot-dmesg detected, turning on logcat banner" >> $LOG
 	ADBANNER=1
 else
-	echo "INFO: boot-dmesg NOT detected, turning off logcat banner"
+	echo "INFO: boot-dmesg NOT detected, turning off logcat banner" >> $LOG
 	ADBANNER=0
 fi
 
 # ArchiDroid Semaphore
 # Wait until we see some android processes to consider boot is more or less complete (credits to AndiP71)
 # Also respect number of loops, maybe something went wrong
-echo "INFO: Init Semaphore started"
+echo "INFO: Init Semaphore started" >> $LOG
 LOOP=0
 while ! pgrep com.android && [ $LOOP -lt 150 ] ; do
 	if [ $ADBANNER -eq 1 ]; then
-		echo ""
-		echo "*******************************************************************************"
-		echo "*             _                _      _  ____               _      _          *"
-		echo "*            / \    _ __  ___ | |__  (_)|  _ \  _ __  ___  (_)  __| |         *"
-		echo "*           / _ \  | '__|/ __|| '_ \ | || | | || '__|/ _ \ | | / _\` |         *"
-		echo "*          / ___ \ | |  | (__ | | | || || |_| || |  | (_) || || (_| |         *"
-		echo "*         /_/   \_\|_|   \___||_| |_||_||____/ |_|   \___/ |_| \__,_|         *"
-		echo "*                                                                             *"
-		echo "*******************************************************************************"
-		echo "*                  _                       _  _                               *"
-		echo "*                 | |     ___    __ _   __| |(_) _ __    __ _                 *"
-		echo "*                 | |    / _ \  / _\` | / _\` || || '_ \  / _\` |                *"
-		echo "*                 | |___| (_) || (_| || (_| || || | | || (_| |                *"
-		echo "*                 |_____|\___/  \__,_| \__,_||_||_| |_| \__, |                *"
-		echo "*                                                       |___/                 *"
-		echo "*******************************************************************************"
-		echo "*            root@ArchiDroid:~# Waiting for ArchiDroid to load...             *"
-		echo "*******************************************************************************"
-		echo ""
+		echo "
+*******************************************************************************
+*             _                _      _  ____               _      _          *
+*            / \    _ __  ___ | |__  (_)|  _ \  _ __  ___  (_)  __| |         *
+*           / _ \  | '__|/ __|| '_ \ | || | | || '__|/ _ \ | | / _\` |         *
+*          / ___ \ | |  | (__ | | | || || |_| || |  | (_) || || (_| |         *
+*         /_/   \_\|_|   \___||_| |_||_||____/ |_|   \___/ |_| \__,_|         *
+*                                                                             *
+*******************************************************************************
+*                  _                       _  _                               *
+*                 | |     ___    __ _   __| |(_) _ __    __ _                 *
+*                 | |    / _ \  / _\` | / _\` || || '_ \  / _\` |                *
+*                 | |___| (_) || (_| || (_| || || | | || (_| |                *
+*                 |_____|\___/  \__,_| \__,_||_||_| |_| \__, |                *
+*                                                       |___/                 *
+*******************************************************************************
+*            root@ArchiDroid:~# Waiting for ArchiDroid to load...             *
+*******************************************************************************
+"
 	fi
 	sleep 2
 done
 
 if [ $LOOP -ge 150 ]; then
-	echo "ERROR: I looped $LOOP times and needed to exit from infinite loop, not good (Init Semaphore)"
+	echo "ERROR: I looped $LOOP times and needed to exit from infinite loop, not good (Init Semaphore)" >> $LOG
 else
-	echo "INFO: I looped $LOOP times and didn't have to exit from infinite loop, that's nice (Init Semaphore)"
+	echo "INFO: I looped $LOOP times and didn't have to exit from infinite loop, that's nice (Init Semaphore)" >> $LOG
 fi
 
 # Now that is checked, let's just wait another tiny little bit
@@ -89,19 +90,19 @@ sleep 5
 
 # Execute a reboot if we need it
 if [ -e /data/media/0/ArchiDroid/HARD_REBOOT_REQUIRED ]; then
-	echo "INFO: HARD_REBOOT_REQUIRED found, I'm rebooting device now..."
+	echo "INFO: HARD_REBOOT_REQUIRED found, I'm rebooting device now..." >> $LOG
 	rm -f /data/media/0/ArchiDroid/SOFT_REBOOT_REQUIRED
 	rm -f /data/media/0/ArchiDroid/HARD_REBOOT_REQUIRED
 	reboot
 elif [ -e /data/media/0/ArchiDroid/SOFT_REBOOT_REQUIRED ]; then
-	echo "INFO: SOFT_REBOOT_REQUIRED found, I'm rebooting android interface now..."
+	echo "INFO: SOFT_REBOOT_REQUIRED found, I'm rebooting android interface now..." >> $LOG
 	rm -f /data/media/0/ArchiDroid/SOFT_REBOOT_REQUIRED
 	killall system_server
 fi
 
 # Finish
-echo "INFO: ArchiDroid Init finished"
-echo "`date`"
+echo "INFO: ArchiDroid Init finished" >> $LOG
+echo "`date`" >> $LOG
 
 # Finish
 exit 0
